### ISSUE TITLE
Fix for borders in HA 2022.11.0 ?

### ISSUE THREAD

**Issue by kalhimeo** [mikosoft83/hass-windows10-themes#4]
Dear developer,

First thank you for the nice theme, I am using it on my wall tablets for some time now :-)

However, since the introduction of the last version of HA (2022.11.0), the layout is somehow f**** because of the new border around the cards layout.

Is there any chance to fix that with a theme update please ?

Thank you very much !

Best regards,
Laurent

**Comment by mikosoft83** [comment]
Thank you very much for the feedback! Yes, I've noticed the borders mentioned in the change log and I'm planning to tackle this once I have my HA instance upgraded (I don't go with .0 release these days since with a child's I don't have much spare time to fix any possible issues).
So please hold on for a couple of days, hopefully no more than two weeks or so.

**Comment by kalhimeo** [comment]
Thanks a lot for the quick feedback ! No worries take your time, got a 1 year old baby myself so I know what you mean ;-)
All the best, cheers !

**Comment by ChristophCaina** [comment]
oh... I see - that with the borders wasn't intensionall on that theme? :D
Since I installed Windows10 Themes 'after' upgrading HA - I didn't catched that - and I have to admit, that I do like the borders - somehow... ^^

Does this look more to the expected layout?
I am not sure about the border on the sidebar...

![grafik](https://user-images.githubusercontent.com/26391061/199842393-d0f8be6a-e46d-48aa-b2d0-864e8a6e4b14.png)
![grafik](https://user-images.githubusercontent.com/26391061/199842376-0eae924a-f2fa-4f26-8ae3-c6a6e218c7f1.png)

If that's ok and the desired behave, I could probably create a PR for this :)

[EDIT]
PR #6

**Comment by mikosoft83** [comment]
Finally got to it, I merged the PR.
I have also modified the template for config generator and will create a new version from all that
